# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Diffusion
else:
    import _Diffusion

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Diffusion.delete_SwigPyIterator

    def value(self):
        return _Diffusion.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Diffusion.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Diffusion.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Diffusion.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Diffusion.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Diffusion.SwigPyIterator_copy(self)

    def next(self):
        return _Diffusion.SwigPyIterator_next(self)

    def __next__(self):
        return _Diffusion.SwigPyIterator___next__(self)

    def previous(self):
        return _Diffusion.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Diffusion.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Diffusion.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Diffusion.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Diffusion.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Diffusion.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Diffusion.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Diffusion.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _Diffusion:
_Diffusion.SwigPyIterator_swigregister(SwigPyIterator)

def Diffusion(edges, weights, SeedSet, T, theta, nNodes, NUMTHREAD):
    return _Diffusion.Diffusion(edges, weights, SeedSet, T, theta, nNodes, NUMTHREAD)
class uintvector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _Diffusion.uintvector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Diffusion.uintvector___nonzero__(self)

    def __bool__(self):
        return _Diffusion.uintvector___bool__(self)

    def __len__(self):
        return _Diffusion.uintvector___len__(self)

    def __getslice__(self, i, j):
        return _Diffusion.uintvector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Diffusion.uintvector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Diffusion.uintvector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Diffusion.uintvector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Diffusion.uintvector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Diffusion.uintvector___setitem__(self, *args)

    def pop(self):
        return _Diffusion.uintvector_pop(self)

    def append(self, x):
        return _Diffusion.uintvector_append(self, x)

    def empty(self):
        return _Diffusion.uintvector_empty(self)

    def size(self):
        return _Diffusion.uintvector_size(self)

    def swap(self, v):
        return _Diffusion.uintvector_swap(self, v)

    def begin(self):
        return _Diffusion.uintvector_begin(self)

    def end(self):
        return _Diffusion.uintvector_end(self)

    def rbegin(self):
        return _Diffusion.uintvector_rbegin(self)

    def rend(self):
        return _Diffusion.uintvector_rend(self)

    def clear(self):
        return _Diffusion.uintvector_clear(self)

    def get_allocator(self):
        return _Diffusion.uintvector_get_allocator(self)

    def pop_back(self):
        return _Diffusion.uintvector_pop_back(self)

    def erase(self, *args):
        return _Diffusion.uintvector_erase(self, *args)

    def __init__(self, *args):
        _Diffusion.uintvector_swiginit(self, _Diffusion.new_uintvector(*args))

    def push_back(self, x):
        return _Diffusion.uintvector_push_back(self, x)

    def front(self):
        return _Diffusion.uintvector_front(self)

    def back(self):
        return _Diffusion.uintvector_back(self)

    def assign(self, n, x):
        return _Diffusion.uintvector_assign(self, n, x)

    def resize(self, *args):
        return _Diffusion.uintvector_resize(self, *args)

    def insert(self, *args):
        return _Diffusion.uintvector_insert(self, *args)

    def reserve(self, n):
        return _Diffusion.uintvector_reserve(self, n)

    def capacity(self):
        return _Diffusion.uintvector_capacity(self)
    __swig_destroy__ = _Diffusion.delete_uintvector

# Register uintvector in _Diffusion:
_Diffusion.uintvector_swigregister(uintvector)
class doublevector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _Diffusion.doublevector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Diffusion.doublevector___nonzero__(self)

    def __bool__(self):
        return _Diffusion.doublevector___bool__(self)

    def __len__(self):
        return _Diffusion.doublevector___len__(self)

    def __getslice__(self, i, j):
        return _Diffusion.doublevector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Diffusion.doublevector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Diffusion.doublevector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Diffusion.doublevector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Diffusion.doublevector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Diffusion.doublevector___setitem__(self, *args)

    def pop(self):
        return _Diffusion.doublevector_pop(self)

    def append(self, x):
        return _Diffusion.doublevector_append(self, x)

    def empty(self):
        return _Diffusion.doublevector_empty(self)

    def size(self):
        return _Diffusion.doublevector_size(self)

    def swap(self, v):
        return _Diffusion.doublevector_swap(self, v)

    def begin(self):
        return _Diffusion.doublevector_begin(self)

    def end(self):
        return _Diffusion.doublevector_end(self)

    def rbegin(self):
        return _Diffusion.doublevector_rbegin(self)

    def rend(self):
        return _Diffusion.doublevector_rend(self)

    def clear(self):
        return _Diffusion.doublevector_clear(self)

    def get_allocator(self):
        return _Diffusion.doublevector_get_allocator(self)

    def pop_back(self):
        return _Diffusion.doublevector_pop_back(self)

    def erase(self, *args):
        return _Diffusion.doublevector_erase(self, *args)

    def __init__(self, *args):
        _Diffusion.doublevector_swiginit(self, _Diffusion.new_doublevector(*args))

    def push_back(self, x):
        return _Diffusion.doublevector_push_back(self, x)

    def front(self):
        return _Diffusion.doublevector_front(self)

    def back(self):
        return _Diffusion.doublevector_back(self)

    def assign(self, n, x):
        return _Diffusion.doublevector_assign(self, n, x)

    def resize(self, *args):
        return _Diffusion.doublevector_resize(self, *args)

    def insert(self, *args):
        return _Diffusion.doublevector_insert(self, *args)

    def reserve(self, n):
        return _Diffusion.doublevector_reserve(self, n)

    def capacity(self):
        return _Diffusion.doublevector_capacity(self)
    __swig_destroy__ = _Diffusion.delete_doublevector

# Register doublevector in _Diffusion:
_Diffusion.doublevector_swigregister(doublevector)
class uintmat(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _Diffusion.uintmat_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Diffusion.uintmat___nonzero__(self)

    def __bool__(self):
        return _Diffusion.uintmat___bool__(self)

    def __len__(self):
        return _Diffusion.uintmat___len__(self)

    def __getslice__(self, i, j):
        return _Diffusion.uintmat___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Diffusion.uintmat___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Diffusion.uintmat___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Diffusion.uintmat___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Diffusion.uintmat___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Diffusion.uintmat___setitem__(self, *args)

    def pop(self):
        return _Diffusion.uintmat_pop(self)

    def append(self, x):
        return _Diffusion.uintmat_append(self, x)

    def empty(self):
        return _Diffusion.uintmat_empty(self)

    def size(self):
        return _Diffusion.uintmat_size(self)

    def swap(self, v):
        return _Diffusion.uintmat_swap(self, v)

    def begin(self):
        return _Diffusion.uintmat_begin(self)

    def end(self):
        return _Diffusion.uintmat_end(self)

    def rbegin(self):
        return _Diffusion.uintmat_rbegin(self)

    def rend(self):
        return _Diffusion.uintmat_rend(self)

    def clear(self):
        return _Diffusion.uintmat_clear(self)

    def get_allocator(self):
        return _Diffusion.uintmat_get_allocator(self)

    def pop_back(self):
        return _Diffusion.uintmat_pop_back(self)

    def erase(self, *args):
        return _Diffusion.uintmat_erase(self, *args)

    def __init__(self, *args):
        _Diffusion.uintmat_swiginit(self, _Diffusion.new_uintmat(*args))

    def push_back(self, x):
        return _Diffusion.uintmat_push_back(self, x)

    def front(self):
        return _Diffusion.uintmat_front(self)

    def back(self):
        return _Diffusion.uintmat_back(self)

    def assign(self, n, x):
        return _Diffusion.uintmat_assign(self, n, x)

    def resize(self, *args):
        return _Diffusion.uintmat_resize(self, *args)

    def insert(self, *args):
        return _Diffusion.uintmat_insert(self, *args)

    def reserve(self, n):
        return _Diffusion.uintmat_reserve(self, n)

    def capacity(self):
        return _Diffusion.uintmat_capacity(self)
    __swig_destroy__ = _Diffusion.delete_uintmat

# Register uintmat in _Diffusion:
_Diffusion.uintmat_swigregister(uintmat)

